name: bgcphaser
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - networkx
  - biopython
  - pyarrow
  - pydantic>=2
  - typer
  - rich
  - pytest
  - spades
  - prodigal
  - hmmer
  - minimap2
  - samtools
  - seqkit
  - pip:
      - -e .
